{% set name = "azure-keyvault-secrets" %}
{% set version = "4.11.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: ac14727b9159cca353173ec5a454d8d7b192a6f2f5e7eb540f9fbcf914fa0ca0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - azure-core >=1.31.0
    - isodate >=0.6.1
    - typing-extensions >=4.6.0

# Test are required devtools_testutils package (azure-devtools) which is not supported by Anaconda.
# Only pip check is performed.
test:
  imports:
    - azure.keyvault.secrets
    - azure.keyvault.secrets.aio
  requires: 
    - pip
  commands: 
    - pip check


about:
  home: https://learn.microsoft.com/en-au/azure/key-vault/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Azure Key Vault Secret client library for Python
  description: |
    Azure Key Vault Secrets client library for Python.
    Azure Key Vault helps solve the following problems:
    - Secrets management (this library) - securely store and control access to tokens, passwords, certificates, API keys, and other secrets
    - Cryptographic key management (azure-keyvault-keys) - create, store, and control access to the keys used to encrypt your data
    - Certificate management (azure-keyvault-certificates) - create, manage, and deploy public and private SSL/TLS certificates
    - Vault administration (azure-keyvault-administration) - role-based access control (RBAC), and vault-level backup and restore options
  doc_url: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/keyvault/azure-keyvault-secrets/README.md
  dev_url: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/keyvault/azure-keyvault-secrets

extra:
  recipe-maintainers:
    - dhirschfeld
